In [2]:
import numpy as np

In [3]:
# Task 1 & 2 #
np.random.seed(421)
a = np.random.randint(5, size=4)
b = np.random.randint(5, size=(2, 3))

In [4]:
a

array([4, 3, 1, 4])

In [5]:
print(b)

[[1 4 0]
 [3 0 0]]


In [6]:
# Task 3 #
a

array([4, 3, 1, 4])

In [7]:
a[1]

3

In [8]:
a[-2]

1

In [9]:
# Task 4 #
b

array([[1, 4, 0],
       [3, 0, 0]])

In [10]:
b[0, 1]

4

In [11]:
b[-1, -2]

0

In [12]:
# Task 5 #
c = np.arange(12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
c[:4]

array([0, 1, 2, 3])

In [14]:
c[0:4:2]

array([0, 2])

In [15]:
c[::3]

array([0, 3, 6, 9])

In [16]:
c[1::2]

array([ 1,  3,  5,  7,  9, 11])

In [17]:
c[5::-1]

array([5, 4, 3, 2, 1, 0])

In [18]:
# Task 6 #
B = b.reshape((3,2))
B

array([[1, 4],
       [0, 3],
       [0, 0]])

In [19]:
# Task 7 #
x1 = [1, 2, 3, 41, 52, 8, 9, 10]
x2 = np.split(x1, [3,5,8])
x2

[array([1, 2, 3]),
 array([41, 52]),
 array([ 8,  9, 10]),
 array([], dtype=int32)]

In [20]:
# Task 8 #
import numpy.linalg

In [21]:
M = np.array([[2,3], [5,-8]])
N = np.array([[1,-4],[8,-6]])

In [22]:
numpy.linalg.inv(M)

array([[ 0.25806452,  0.09677419],
       [ 0.16129032, -0.06451613]])

In [23]:
numpy.linalg.det(N)

25.99999999999999

In [2]:
# Task 9 #
x2 = [-10, 2, 3, -5]

In [3]:
np.abs(x2)

array([10,  2,  3,  5])

In [7]:
np.add(x2, 4)

array([-6,  6,  7, -1])

In [8]:
np.subtract(x2, 3)

array([-13,  -1,   0,  -8])

In [10]:
np.multiply(x2, -2)

array([20, -4, -6, 10])

In [11]:
np.mod(x2, 2)

array([0, 0, 1, 1], dtype=int32)

In [17]:
# Task 10 #
np.equal(x2,2)

array([False,  True, False, False])

In [18]:
np.not_equal(x2,2)

array([ True, False,  True,  True])

In [19]:
np.less(x2,2)

array([ True, False, False,  True])

In [20]:
np.less_equal(x2, 2)

array([ True,  True, False,  True])

In [22]:
np.greater(x2,2)

array([False, False,  True, False])

In [23]:
np.greater_equal(x2,2)

array([False,  True,  True, False])

In [24]:
# Task 11 #
np.sum(x2)

-10

In [25]:
np.prod(x2)

300

In [26]:
np.mean(x2)

-2.5

In [27]:
np.std(x2)

5.315072906367325

In [28]:
np.var(x2)

28.25

In [29]:
np.min(x2)

-10

In [30]:
np.max(x2)

3

In [32]:
np.argmin(x2)

0

In [33]:
np.argmax(x2)

2

In [34]:
np.median(x2)

-1.5

In [35]:
np.any(x2)

True

In [36]:
np.all(x2)

True

In [37]:
# Task 12 #
x3 = np.arange(15)
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
x = np.prod(x3[(x3<10) & (x3>3)])
x

60480

In [39]:
# Task 13 #
rand = np.random.RandomState(421)
rx = rand.randint(50, size=10)
rx

array([23, 44, 19, 17, 15, 30, 38, 17, 47, 32])

In [40]:
indices = np.random.choice(rx.shape[0], 5, replace=False)
indices

array([5, 7, 6, 0, 8])

In [41]:
selected = rx[indices]
print(selected)

[30 17 38 23 47]


In [42]:
rx[indices] = 0

In [43]:
print(rx)

[ 0 44 19 17 15  0  0  0  0 32]


In [24]:
# Task 14 #
x4 = [10, 9, -1, 3]

In [25]:
np.sort(x4)

array([-1,  3,  9, 10])

In [26]:
np.sort(x4)[::-1]

array([10,  9,  3, -1])