In [1]:
#For help in python use 
#help()

#Or use help(len) for getting info about len or anything
#help(len)

#Or for knowing somethin use ? sign ex:
#len?

In [3]:
#Importing numpy, it provides an efficient interface to store and operate on dense data buffers
import numpy as np

#Version checking of numpy
np.__version__

#To display all the contents of the numpy namespace
np?

In [31]:
#Generate an array using Numpy
arr=np.array([1,2,3,4])
print(arr)

#Numpy random array
np.random.seed(421) #By mentioning seed() to a particular number, you are hanging on to same set of random numbers always.
arr2=np.random.randint(50,size=4) #One dimensiona array within 50 size 4
print(arr2)

arr3=np.random.randint(50,size=(2,3)) #Two dimensional array within 50
print(arr3)

#Array dimension
print(arr2.ndim)
print(arr3.ndim)

#Array size
print(arr2.size) #total
print(arr3.size)

#Array shape
print(arr2.shape) #no of rows and columns
print(arr3.shape)

#Array Datatype
print(arr2.dtype)

#Array element size in byte
print(arr2.itemsize)

#Array total size in bytes
print(arr2.nbytes)

#Array individual index value in one dimensional
print(arr2[0])

#To index from the end of the array, you can use negative indices. 
print(arr2[-4])

#Array individual index value in two dimensional
print(arr3[0,1])


[1 2 3 4]
[23 44 19 17]
[[15 30 38]
 [17 47 32]]
1
2
4
6
(4,)
(2, 3)
int32
4
16
23
23
30


In [57]:
#Slicing an array - x[start:stop:step]. One dimensional
print(arr2[0:3])
print(arr2[0:4:3])
print(arr2[3:0:-1])
print(arr2[3::-1])

#Slicing array two dimensional array - x[start:stop:step, start:stop:step]
print(arr3[0:1,0:3:2])

#Array creating with arrange - 
#np.arange?
print(np.arange(10))

[23 44 19]
[23 17]
[17 19 44]
[17 19 44 23]
[[15 38]]
[0 1 2 3 4 5 6 7 8 9]


In [80]:
#You can change the shape of a given array by using the reshape() method
x=np.arange(10)
print(x.reshape((5,2))) #Must hold all elements

#Concatenation and splitting
np.concatenate([x,x],axis=0) #axis 0 means adding elements in first dimension
np.concatenate([arr3,arr3],axis=0) #Must be in same dimension


#Splitting array
np.split(x,2)
#np.split(x,[2,5,8,10])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[array([0, 1]),
 array([2, 3, 4]),
 array([5, 6, 7]),
 array([8, 9]),
 array([], dtype=int32)]

In [105]:
#Matrices 
M=[[1,2,3],[4,5,6]]
print(M[0][2])

N=np.array([[1,2,3],[4,5,6]])
print(N[0,2])

P=np.random.randint(6,size=(2,3))
print(P)

K=P-N
print(K)

print(P*2)
print(P**2)
L=np.random.randint(6,size=(3,2))

#Matrix Multiplication
print(P@L)
print(P.dot(L))

3
3
[[1 2 3]
 [1 3 4]]
[[ 0  0  0]
 [-3 -2 -2]]
[[2 4 6]
 [2 6 8]]
[[ 1  4  9]
 [ 1  9 16]]
[[25 15]
 [34 20]]
[[25 15]
 [34 20]]


In [109]:
#Matrix Transpose
print(np.transpose(N))

#Matrix Trace
print(np.trace(N))

#Matrix Diagonal elements
print(np.diag(N))

[[1 4]
 [2 5]
 [3 6]]
6
[1 5]


In [145]:
#numpy.linalg is a class having a standard set of things like inverse and determinant. matrix decompositions. 
import numpy.linalg as li
Q=np.random.randint(4,size=(2,2))
print(Q)

#Matrix determinant
det=li.det(Q)
print(det)

#Matrix Inverse operation
if det!=0:
    print(li.inv(Q))
else:
    print("Not Possible")
    
#Matrix conditions
print(N,P)
if N.all() == P.all():
    print("Yes Equal")
else:
    print("Not Equal")

[[0 3]
 [3 1]]
-9.000000000000002
[[-0.11111111  0.33333333]
 [ 0.33333333  0.        ]]
[[1 2 3]
 [4 5 6]] [[1 2 3]
 [1 3 4]]
Not Equal


In [153]:
#Max, Min   
print(P)
print(P.max())
print(P.argmax()) #Index of maximum element 
print(P.argmin())

#Sum and Product of all elements
print(P.sum())  #nansum or nanprod is best to use
print(P.prod())

#Sum of specific values
print(np.sum(P[(P>=1)&(P<=2)])) #Sum of all elements between 1 and 2 values inclusive


[[1 2 3]
 [1 3 4]]
4
5
0
14
72
4


In [156]:
#Choosing random data points
T=np.random.randint(100,size=20)
print(T)
indices=np.random.choice(T.shape[0],5,replace=False)
print(indices)
print(T[indices])

[ 5 67 27 82 66 76 79 36 83 35 37 84 60 82 50 36 58 68 29 12]
[ 8  1 13  4 15]
[83 67 82 66 36]
